version: '3.8'

services:
  # 프로덕션 프론트엔드
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VUE_APP_API_URL=https://api.lotto-analysis.com
    depends_on:
      - backend

  # 프로덕션 백엔드
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=lotto_analysis
      - DB_USERNAME=lotto_user
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_KEY=${APP_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - database
      - redis
    volumes:
      - ./backend/storage:/var/www/storage
      - ./backend/bootstrap/cache:/var/www/bootstrap/cache

  # 프로덕션 데이터베이스
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: lotto_analysis
      MYSQL_USER: lotto_user
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # 프로덕션 Redis
  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: